name: Output hello.txt's content

on:
  push:
    branches:
      - master

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Output hello.txt's content
        run: cat hello.txt